version: '2'

services:

  midi:
    image : dgoldstein1/midiservice
    expose:
      - 8080
    ports: 
      - "8080:8080"
    environment:
      - S3_ACCESS_KEY
      - S3_SECRET_ACCESS_KEY
      - S3_BUCKET_NAME
      - S3_BUCKET_URL
      - S3_FOLDER_PATH
